### ISSUE TITLE
how to write the command?

### ISSUE THREAD

**Issue by luckypoem** [fardog/dnoxy#1]
hi.

i use dnoxy-dns successfully:
sudo dnoxy-dns -listen :53 -endpoint https://mydomain.com/dns-query -tcp true -udp true 

but about dnoxy-http,
sudo dnoxy-http -listen :53 -endpoint mydomain.com:443 -path /dns-query
it shows:
[mydomain.com:443]
INFO[0000] listening on :53  

but i failed to use the command "sudo dnoxy-http -listen :53 -endpoint mydomain.com:443 -path /dns-query" to connect to my doh server: https://mydomain.com/dns-query ,is the command not correct?

**Comment by fardog** [comment]
the `dnoxy-http` endpoints should be DNS servers, not http servers, such as:

```
dnoxy-http -listen :80 -endpoint 8.8.8.8 -path /dns-query
```

this will start a DNS-over-HTTP server on port 80, which forwards requests to google DNS
